# Generated by Django 4.0 on 2023-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('LncRNA_id', models.CharField(max_length=25)),
                ('LncRNA_uid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Chr', models.CharField(max_length=50)),
                ('Start', models.BigIntegerField()),
                ('End', models.BigIntegerField()),
                ('Strand', models.CharField(max_length=2)),
                ('TSS', models.CharField(max_length=50)),
                ('Promoter_start', models.CharField(max_length=50)),
                ('Promoter_end', models.CharField(max_length=50)),
                ('Length', models.CharField(max_length=50)),
                ('Exon_number', models.CharField(max_length=50)),
                ('Tr_Class', models.CharField(max_length=25)),
                ('Tr_Direction', models.CharField(max_length=150)),
                ('Tr_Location', models.CharField(max_length=150)),
                ('Expression_status', models.CharField(max_length=150)),
                ('Orthologs_status', models.CharField(max_length=150)),
                ('Overlap_gene_id', models.CharField(max_length=150)),
                ('Overlap_ref_id', models.CharField(max_length=150)),
                ('Class_code', models.CharField(max_length=5)),
                ('Organism', models.CharField(max_length=15)),
                ('Orthologs_Human', models.CharField(max_length=1000)),
                ('Orthologs_Chimp', models.CharField(max_length=1000)),
                ('Orthologs_Gorilla', models.CharField(max_length=1000)),
                ('Orthologs_Gibbon', models.CharField(max_length=1000)),
                ('DEG_Human', models.CharField(max_length=800)),
                ('DEG_Chimp', models.CharField(max_length=800)),
                ('Sequence', models.TextField()),
            ],
            options={
                'db_table': 'General_Info',
            },
        ),
        migrations.CreateModel(
            name='UserOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=25)),
                ('Organization', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
    ]
